package robotarmedge.view;

/**
 * 
 * 
 * @author Joshua Michael Daly
 */
public class BasicMode extends javax.swing.JFrame
{

    /**
     * Creates new form BasicMode
     */
    public BasicMode()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        closeGripperButton = new javax.swing.JButton();
        openGripperButton = new javax.swing.JButton();
        wristDownButton = new javax.swing.JButton();
        wristUpButton = new javax.swing.JButton();
        elbowUpButton = new javax.swing.JButton();
        elbowDownButton = new javax.swing.JButton();
        armDownButton = new javax.swing.JButton();
        armUpButton = new javax.swing.JButton();
        toggleLightButton = new javax.swing.JButton();
        baseLeftButton = new javax.swing.JButton();
        baseRightButton = new javax.swing.JButton();
        toggleModeButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        basicModeLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        armImagePanel = new javax.swing.JPanel();
        outputLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Basic Mode");
        setMaximumSize(new java.awt.Dimension(790, 565));
        setMinimumSize(new java.awt.Dimension(790, 565));
        setName("BasicModeFrame"); // NOI18N
        setResizable(false);

        closeGripperButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/robotarmedge/resources/arrow-curve-090.png"))); // NOI18N
        closeGripperButton.setText("W");
        closeGripperButton.setToolTipText("Close Gripper");
        closeGripperButton.setMaximumSize(new java.awt.Dimension(70, 50));
        closeGripperButton.setMinimumSize(new java.awt.Dimension(70, 50));
        closeGripperButton.setPreferredSize(new java.awt.Dimension(70, 50));
        closeGripperButton.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                closeGripperButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                closeGripperButtonMouseReleased(evt);
            }
        });

        openGripperButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/robotarmedge/resources/arrow-curve-270.png"))); // NOI18N
        openGripperButton.setText("S");
        openGripperButton.setToolTipText("Open Gripper");
        openGripperButton.setMaximumSize(new java.awt.Dimension(70, 50));
        openGripperButton.setMinimumSize(new java.awt.Dimension(70, 50));
        openGripperButton.setPreferredSize(new java.awt.Dimension(70, 50));
        openGripperButton.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                openGripperButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                openGripperButtonMouseReleased(evt);
            }
        });

        wristDownButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/robotarmedge/resources/arrow-curve-270.png"))); // NOI18N
        wristDownButton.setText("D");
        wristDownButton.setToolTipText("Wrist Down");
        wristDownButton.setMaximumSize(new java.awt.Dimension(70, 50));
        wristDownButton.setMinimumSize(new java.awt.Dimension(70, 50));
        wristDownButton.setPreferredSize(new java.awt.Dimension(70, 50));
        wristDownButton.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                wristDownButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                wristDownButtonMouseReleased(evt);
            }
        });

        wristUpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/robotarmedge/resources/arrow-curve-090.png"))); // NOI18N
        wristUpButton.setText("E");
        wristUpButton.setToolTipText("Wrist Up");
        wristUpButton.setMaximumSize(new java.awt.Dimension(70, 50));
        wristUpButton.setMinimumSize(new java.awt.Dimension(70, 50));
        wristUpButton.setPreferredSize(new java.awt.Dimension(70, 50));
        wristUpButton.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                wristUpButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                wristUpButtonMouseReleased(evt);
            }
        });

        elbowUpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/robotarmedge/resources/arrow-curve-090.png"))); // NOI18N
        elbowUpButton.setText("R");
        elbowUpButton.setToolTipText("Elbow Up");
        elbowUpButton.setMaximumSize(new java.awt.Dimension(70, 50));
        elbowUpButton.setMinimumSize(new java.awt.Dimension(70, 50));
        elbowUpButton.setPreferredSize(new java.awt.Dimension(70, 50));
        elbowUpButton.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                elbowUpButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                elbowUpButtonMouseReleased(evt);
            }
        });

        elbowDownButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/robotarmedge/resources/arrow-curve-270.png"))); // NOI18N
        elbowDownButton.setText("F");
        elbowDownButton.setToolTipText("Elbow Down");
        elbowDownButton.setMaximumSize(new java.awt.Dimension(70, 50));
        elbowDownButton.setMinimumSize(new java.awt.Dimension(70, 50));
        elbowDownButton.setPreferredSize(new java.awt.Dimension(70, 50));
        elbowDownButton.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                elbowDownButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                elbowDownButtonMouseReleased(evt);
            }
        });

        armDownButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/robotarmedge/resources/arrow-curve-270.png"))); // NOI18N
        armDownButton.setText("J");
        armDownButton.setToolTipText("Arm Down");
        armDownButton.setMaximumSize(new java.awt.Dimension(70, 50));
        armDownButton.setMinimumSize(new java.awt.Dimension(70, 50));
        armDownButton.setPreferredSize(new java.awt.Dimension(70, 50));
        armDownButton.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                armDownButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                armDownButtonMouseReleased(evt);
            }
        });

        armUpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/robotarmedge/resources/arrow-curve-090.png"))); // NOI18N
        armUpButton.setText("U");
        armUpButton.setToolTipText("Arm Up");
        armUpButton.setMaximumSize(new java.awt.Dimension(70, 50));
        armUpButton.setMinimumSize(new java.awt.Dimension(70, 50));
        armUpButton.setPreferredSize(new java.awt.Dimension(70, 50));
        armUpButton.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                armUpButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                armUpButtonMouseReleased(evt);
            }
        });

        toggleLightButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/robotarmedge/resources/light-bulb-off.png"))); // NOI18N
        toggleLightButton.setText("L");
        toggleLightButton.setToolTipText("Toggle Light");
        toggleLightButton.setMaximumSize(new java.awt.Dimension(70, 50));
        toggleLightButton.setMinimumSize(new java.awt.Dimension(70, 50));
        toggleLightButton.setPreferredSize(new java.awt.Dimension(70, 50));
        toggleLightButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                toggleLightButtonActionPerformed(evt);
            }
        });

        baseLeftButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/robotarmedge/resources/arrow-circle-anticlockwise.png"))); // NOI18N
        baseLeftButton.setText("K");
        baseLeftButton.setToolTipText("Base Left");
        baseLeftButton.setMaximumSize(new java.awt.Dimension(70, 50));
        baseLeftButton.setMinimumSize(new java.awt.Dimension(70, 50));
        baseLeftButton.setPreferredSize(new java.awt.Dimension(70, 50));
        baseLeftButton.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                baseLeftButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                baseLeftButtonMouseReleased(evt);
            }
        });

        baseRightButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/robotarmedge/resources/arrow-circle.png"))); // NOI18N
        baseRightButton.setText("I");
        baseRightButton.setToolTipText("Base Right");
        baseRightButton.setMaximumSize(new java.awt.Dimension(70, 50));
        baseRightButton.setMinimumSize(new java.awt.Dimension(70, 50));
        baseRightButton.setPreferredSize(new java.awt.Dimension(70, 50));
        baseRightButton.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                baseRightButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                baseRightButtonMouseReleased(evt);
            }
        });

        toggleModeButton.setText("MODE");
        toggleModeButton.setToolTipText("Toggle Mode");
        toggleModeButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                toggleModeButtonActionPerformed(evt);
            }
        });

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/robotarmedge/resources/cross.png"))); // NOI18N
        closeButton.setText("CLOSE");
        closeButton.setToolTipText("Close");
        closeButton.setMaximumSize(new java.awt.Dimension(70, 50));
        closeButton.setMinimumSize(new java.awt.Dimension(70, 50));
        closeButton.setPreferredSize(new java.awt.Dimension(70, 50));
        closeButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                closeButtonActionPerformed(evt);
            }
        });

        basicModeLabel.setText("BASIC MODE");
        basicModeLabel.setToolTipText("Basic Mode");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        armImagePanel.setBackground(new java.awt.Color(255, 128, 0));
        armImagePanel.setMaximumSize(new java.awt.Dimension(647, 42));
        armImagePanel.setMinimumSize(new java.awt.Dimension(647, 42));

        outputLabel.setText("jLabel1");

        javax.swing.GroupLayout armImagePanelLayout = new javax.swing.GroupLayout(armImagePanel);
        armImagePanel.setLayout(armImagePanelLayout);
        armImagePanelLayout.setHorizontalGroup(
            armImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, armImagePanelLayout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addComponent(outputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
        );
        armImagePanelLayout.setVerticalGroup(
            armImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(armImagePanelLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(outputLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(basicModeLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(toggleModeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(closeGripperButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(openGripperButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(wristDownButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wristUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(elbowDownButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(elbowUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(armDownButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(armUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(baseLeftButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(baseRightButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toggleLightButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(162, 162, 162))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(armImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(basicModeLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 337, Short.MAX_VALUE)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(armImagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(baseLeftButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(armUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(toggleLightButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(baseRightButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(armDownButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(elbowUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(elbowDownButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(wristUpButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(closeGripperButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(wristDownButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(openGripperButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(toggleModeButton, javax.swing.GroupLayout.Alignment.TRAILING)))))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toggleModeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_toggleModeButtonActionPerformed
    {//GEN-HEADEREND:event_toggleModeButtonActionPerformed
        this.outputLabel.setText("Mode changed.");
    }//GEN-LAST:event_toggleModeButtonActionPerformed

    private void closeGripperButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_closeGripperButtonMousePressed
    {//GEN-HEADEREND:event_closeGripperButtonMousePressed
        this.outputLabel.setText("Gripper Close Pressed.");
    }//GEN-LAST:event_closeGripperButtonMousePressed

    private void closeGripperButtonMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_closeGripperButtonMouseReleased
    {//GEN-HEADEREND:event_closeGripperButtonMouseReleased
        this.outputLabel.setText("Gripper Close Released");
    }//GEN-LAST:event_closeGripperButtonMouseReleased

    private void openGripperButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_openGripperButtonMousePressed
    {//GEN-HEADEREND:event_openGripperButtonMousePressed
        this.outputLabel.setText("Gripper Open Pressed.");
    }//GEN-LAST:event_openGripperButtonMousePressed

    private void openGripperButtonMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_openGripperButtonMouseReleased
    {//GEN-HEADEREND:event_openGripperButtonMouseReleased
        this.outputLabel.setText("Gripper Open Released.");
    }//GEN-LAST:event_openGripperButtonMouseReleased

    private void wristUpButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_wristUpButtonMousePressed
    {//GEN-HEADEREND:event_wristUpButtonMousePressed
        this.outputLabel.setText("Wrist Up Pressed.");
    }//GEN-LAST:event_wristUpButtonMousePressed

    private void wristUpButtonMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_wristUpButtonMouseReleased
    {//GEN-HEADEREND:event_wristUpButtonMouseReleased
        this.outputLabel.setText("Wrist Up Released.");
    }//GEN-LAST:event_wristUpButtonMouseReleased

    private void wristDownButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_wristDownButtonMousePressed
    {//GEN-HEADEREND:event_wristDownButtonMousePressed
        this.outputLabel.setText("Wrist Down Pressed.");
    }//GEN-LAST:event_wristDownButtonMousePressed

    private void wristDownButtonMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_wristDownButtonMouseReleased
    {//GEN-HEADEREND:event_wristDownButtonMouseReleased
       this.outputLabel.setText("Wrist Down Released.");
    }//GEN-LAST:event_wristDownButtonMouseReleased

    private void elbowUpButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_elbowUpButtonMousePressed
    {//GEN-HEADEREND:event_elbowUpButtonMousePressed
        this.outputLabel.setText("Elbow Up Pressed.");
    }//GEN-LAST:event_elbowUpButtonMousePressed

    private void elbowUpButtonMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_elbowUpButtonMouseReleased
    {//GEN-HEADEREND:event_elbowUpButtonMouseReleased
        this.outputLabel.setText("Elbow Up Released.");
    }//GEN-LAST:event_elbowUpButtonMouseReleased

    private void elbowDownButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_elbowDownButtonMousePressed
    {//GEN-HEADEREND:event_elbowDownButtonMousePressed
        this.outputLabel.setText("Elbow Down Pressed.");
    }//GEN-LAST:event_elbowDownButtonMousePressed

    private void elbowDownButtonMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_elbowDownButtonMouseReleased
    {//GEN-HEADEREND:event_elbowDownButtonMouseReleased
        this.outputLabel.setText("Elbow Down Released.");
    }//GEN-LAST:event_elbowDownButtonMouseReleased

    private void armUpButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_armUpButtonMousePressed
    {//GEN-HEADEREND:event_armUpButtonMousePressed
        this.outputLabel.setText("Arm Up Pressed.");
    }//GEN-LAST:event_armUpButtonMousePressed

    private void armUpButtonMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_armUpButtonMouseReleased
    {//GEN-HEADEREND:event_armUpButtonMouseReleased
        this.outputLabel.setText("Arm Up Released.");
    }//GEN-LAST:event_armUpButtonMouseReleased

    private void armDownButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_armDownButtonMousePressed
    {//GEN-HEADEREND:event_armDownButtonMousePressed
        this.outputLabel.setText("Arm Down Pressed.");
    }//GEN-LAST:event_armDownButtonMousePressed

    private void armDownButtonMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_armDownButtonMouseReleased
    {//GEN-HEADEREND:event_armDownButtonMouseReleased
        this.outputLabel.setText("Arm Down Released.");
    }//GEN-LAST:event_armDownButtonMouseReleased

    private void baseRightButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_baseRightButtonMousePressed
    {//GEN-HEADEREND:event_baseRightButtonMousePressed
        this.outputLabel.setText("Base Right Pressed.");
    }//GEN-LAST:event_baseRightButtonMousePressed

    private void baseRightButtonMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_baseRightButtonMouseReleased
    {//GEN-HEADEREND:event_baseRightButtonMouseReleased
        this.outputLabel.setText("Base Right Released.");
    }//GEN-LAST:event_baseRightButtonMouseReleased

    private void baseLeftButtonMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_baseLeftButtonMousePressed
    {//GEN-HEADEREND:event_baseLeftButtonMousePressed
        this.outputLabel.setText("Base Left Pressed.");
    }//GEN-LAST:event_baseLeftButtonMousePressed

    private void baseLeftButtonMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_baseLeftButtonMouseReleased
    {//GEN-HEADEREND:event_baseLeftButtonMouseReleased
        this.outputLabel.setText("Base Left Released.");
    }//GEN-LAST:event_baseLeftButtonMouseReleased

    private void toggleLightButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_toggleLightButtonActionPerformed
    {//GEN-HEADEREND:event_toggleLightButtonActionPerformed
        this.outputLabel.setText("Light Toggled.");
    }//GEN-LAST:event_toggleLightButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_closeButtonActionPerformed
    {//GEN-HEADEREND:event_closeButtonActionPerformed
        this.outputLabel.setText("Close Pressed.");
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(BasicMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(BasicMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(BasicMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(BasicMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new BasicMode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton armDownButton;
    private javax.swing.JPanel armImagePanel;
    private javax.swing.JButton armUpButton;
    private javax.swing.JButton baseLeftButton;
    private javax.swing.JButton baseRightButton;
    private javax.swing.JLabel basicModeLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton closeGripperButton;
    private javax.swing.JButton elbowDownButton;
    private javax.swing.JButton elbowUpButton;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JButton openGripperButton;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JButton toggleLightButton;
    private javax.swing.JButton toggleModeButton;
    private javax.swing.JButton wristDownButton;
    private javax.swing.JButton wristUpButton;
    // End of variables declaration//GEN-END:variables
}
