package robotarmedge.view;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import robotarmedge.device.UsbRobotArm;

/**
 * 
 * 
 * @author Joshua Michael Daly
 */
public class SelectMode extends javax.swing.JFrame
{

    /*
     * ************************************************************************* 
     * Public Constructors
     * *************************************************************************
     */
    /**
     * Creates new form SelectMode
     */
    public SelectMode()
    {
        initComponents();
    }

    /*
     * ************************************************************************* 
     * Private Methods
     * *************************************************************************
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        basicButton = new javax.swing.JButton();
        programButton = new javax.swing.JButton();
        aboutButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Select Mode");
        setResizable(false);

        basicButton.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        basicButton.setText("Basic");
        basicButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                basicButtonActionPerformed(evt);
            }
        });

        programButton.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        programButton.setText("Program");
        programButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                programButtonActionPerformed(evt);
            }
        });

        aboutButton.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        aboutButton.setText("About");
        aboutButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                aboutButtonActionPerformed(evt);
            }
        });

        quitButton.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                quitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(basicButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(programButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(aboutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(basicButton)
                    .addComponent(programButton))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quitButton)
                    .addComponent(aboutButton))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void basicButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_basicButtonActionPerformed
    {//GEN-HEADEREND:event_basicButtonActionPerformed
        this.setVisible(false);
        
        BasicMode basicMode = new BasicMode(UsbRobotArm.getInstance());
        basicMode.addWindowListener(new CloseListener());
        basicMode.setLocationRelativeTo(null);
        basicMode.setVisible(true);
    }//GEN-LAST:event_basicButtonActionPerformed

    private void programButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_programButtonActionPerformed
    {//GEN-HEADEREND:event_programButtonActionPerformed
        this.setVisible(false);
        
        ProgramMode programMode = new ProgramMode(UsbRobotArm.getInstance());
        programMode.addWindowListener(new CloseListener());
        programMode.setLocationRelativeTo(null);
        programMode.setVisible(true);
    }//GEN-LAST:event_programButtonActionPerformed

    private void aboutButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aboutButtonActionPerformed
    {//GEN-HEADEREND:event_aboutButtonActionPerformed
        AboutDialog aboutDialog = new AboutDialog(this, true);
        aboutDialog.setLocationRelativeTo(this);
        aboutDialog.setVisible(true);
    }//GEN-LAST:event_aboutButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_quitButtonActionPerformed
    {//GEN-HEADEREND:event_quitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(SelectMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(SelectMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(SelectMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(SelectMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new SelectMode().setVisible(true);
            }
        });
    }
    
    /*
     * ************************************************************************* 
     * Private Inner Classes
     * *************************************************************************
     */
    private class CloseListener extends WindowAdapter
    {
        @Override
        public void windowClosed(WindowEvent evt)
        {
            setLocationRelativeTo(null);
            setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutButton;
    private javax.swing.JButton basicButton;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton programButton;
    private javax.swing.JButton quitButton;
    // End of variables declaration//GEN-END:variables

}
